spring:
  application:
    name: gatewayMS
  cloud:
    consul:
      host: localhost
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedHeaders: "*"
            allowedMethods:
            - GET
            - POST
            - PUT
            - DELETE
      discovery:
        locator:
          enabled: true
      routes:
        - id: customerMS
          uri: lb://customerMS
          predicates:
            - Path=/customer/**
        - id: cartMS
          uri: lb://cartMS
          predicates:
            - Path=/cart/**
        - id: paymentMS
          uri: lb://paymentMS
          predicates:
            - Path=/payment/**
        - id: audiobookMS
          uri: lb://audiobookMS
          predicates:
            - Path=/audiobook/**
          

server:
  port: 2000